server {
    listen 80;
    server_name parkly.localhost;

    root /var/www/frontend;
    index index.html;

    # Frontend (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API backend (Apache)
location /api/ {
    rewrite ^/api(/.*)?$ $1 break;
    proxy_pass http://web:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}



    # PHP direct
    location ~ \.php$ {
        proxy_pass http://web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # phpMyAdmin
    location /pma/ {
        proxy_pass http://phpmyadmin:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;

        sub_filter_once off;
        sub_filter 'href="/' 'href="/pma/';
        sub_filter 'src="/' 'src="/pma/';
        sub_filter 'action="/' 'action="/pma/';
    }
}
